brew install --cask zoom
brew install --cask devonthink
brew install --cask audacity
brew install --cask calibre
brew install --cask descript
brew install --cask devonthink
brew install --cask dropbox
brew install --cask balenaetcher
brew install --cask iterm2
brew install --cask omnifocus
brew install --cask firefox
brew install --cask google-chrome
brew install --cask 1password
brew install --cask obsidian
brew install --cask rstudio
brew install --cask scrivener
brew install --cask spotify
brew install --cask steam
brew install --cask zotero
brew install --cask alfred
brew install --cask appcleaner
brew install --cask iterm2
